### PR TITLE
WIP - MF fix Issues #91 and #92 (tabled until library restructured)

### PR DESCRIPTION
**Pull request by MeganFantes**

### CODE REVIEW

**Comment by globusharris** [comment]
1. Laplace mechanism: Decided to allow users to determine imputation for numeric data for the histogram statistic. This entails adding a check before calling fillMissing to see if .self$impute is true or false.
* Problem: we don't want other statistics to have the option to not impute data (at least not yet, we'll need to change the mechanism called if we want this since e.g. sensitivity of the mean changes with missing values)
* Solution: make the .self$impute variable specific to the histogram statistic
  * Problem: histogram statistic is subclass of mechanism class, and from cursory inspection it appears that you're not allowed to introduce variables specific to subclasses.

- [ ] Verify that this issue with variables in subclasses is the case? If not we're good.
- [ ] If it is the case, can add global default to make .self$impute true but not crazy about that so hopefully can find another way. Revisit if we actually want to do this if we can't make it a local variable.
- [ ] Add check before call to fillMissing in Laplace mechanism.

2. Verify that NA bucket is created in stability mechanism when NA values exist

- [ ] Add option to determine imputation for numeric data here as well.

**Comment by globusharris** [comment]
DO NOT MERGE YET

**Comment by MeganFantes** [comment]
Ira and I discussed this at length, and we decided these issues should be tabled for now.

Given the way the library is structured now, where there are `export()` statements in the statistics to call the mechanisms, there is no logical way to set a local attribute in a subclass and the check for its existence.

We plan to do major restructuring of the library to have the mechanisms and statistics be completely separate entities, and in this case it will be more possible to set `impute` as an attribute of only the histogram statistic.

When the library is restructured, we can revisit the issue of conditioning the call to `fillMissing()` on `impute` for the histogram statistic.

**Comment by globusharris** [comment]
Doesn't really make sense to restructure library when we are just porting to rust so closing this for now.

**Pull request closed without merging**
